[project]
name = "assetlife"
version = "0.1.1.dev1"
description = "Python library leveraging stochastic modeling to guide decision-making in asset management"
readme = "README.md"
authors = [{name = "Thomas Guillon et al."}]
maintainers = [{name = "AssetLife Developers"}]
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.4.6",
    "numpydoc>=1.10.0",
    "optype[numpy]>=0.17.1",
    "scipy>=1.17.1",
    "typing-extensions>=4.16.0",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[dependency-groups]
extra = [
    "jupyterlab>=4.6.3",
]
doc = [
	{ include-group = "extra" },
    "nbsphinx>=0.9.8",
    "pydata-sphinx-theme>=0.21.0",
    "sphinx>=9.0.4",
    "sphinx-copybutton>=0.5.2",
    "sphinx-design>=0.7.0",
]
lint = [
    "ruff>=0.16.6",
]
format = [
	{ include-group = "lint" },
]
test = [
    "lifelines>=0.30.3",
    "pytest>=9.1.1",
]
type = [
    "basedpyright>=1.40.0",
    "matplotlib-stubs>=0.3.11",
    "mypy>=2.3.1",
    "scipy-stubs>=1.17.1.5",
]
dev = [
	{ include-group = "extra" },
	{ include-group = "doc" },
	{ include-group = "lint" },
	{ include-group = "format" },
	{ include-group = "test" },
	{ include-group = "type" },
]
